### ISSUE TITLE
first start of ansible-lint cant create dirs

### ISSUE THREAD

**Issue by philippmayrth** [philippmayrth/ansible-runner#1]
See how this can be overcome. It occures because Jenkins is pulling the container but then not executing the commands as root but as a user with the same id its user on the host system has.
-> Maybe do a "dry-run" on image creation

```
[workspace] Running shell script

+ ansible-lint server.yml

Unhandled error:

 Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/ansible/config/manager.py", line 523, in update_config_data

    value, origin = self.get_config_value_and_origin(config, configfile)

  File "/usr/local/lib/python2.7/dist-packages/ansible/config/manager.py", line 467, in get_config_value_and_origin

    value = ensure_type(value, defs[config].get('type'), origin=origin)

  File "/usr/local/lib/python2.7/dist-packages/ansible/config/manager.py", line 110, in ensure_type

    makedirs_safe(value, 0o700)

  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/path.py", line 82, in makedirs_safe

    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))

AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: '/.ansible'





Traceback (most recent call last):

  File "/usr/local/bin/ansible-lint", line 7, in <module>

    from ansiblelint.__main__ import main

  File "/usr/local/lib/python2.7/dist-packages/ansiblelint/__init__.py", line 29, in <module>

    import ansiblelint.utils

  File "/usr/local/lib/python2.7/dist-packages/ansiblelint/utils.py", line 26, in <module>

    from ansible import constants

  File "/usr/local/lib/python2.7/dist-packages/ansible/constants.py", line 189, in <module>

    config = ConfigManager()

  File "/usr/local/lib/python2.7/dist-packages/ansible/config/manager.py", line 263, in __init__

    self.update_config_data()

  File "/usr/local/lib/python2.7/dist-packages/ansible/config/manager.py", line 535, in update_config_data

    raise AnsibleError("Invalid settings supplied for %s: %s\n" % (config, to_native(e)), orig_exc=e)

ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: '/.ansible'



script returned exit code 1
```

**Comment by philippmayrth** [comment]
> -> Maybe do a "dry-run" on image creation

Did not work. Same issue here.

**Comment by philippmayrth** [comment]
Next Step: Try with https://stackoverflow.com/questions/44791060/run-jenkins-pipeline-agent-with-sudo especially this looks promising https://github.com/sudo-bmitch/jenkins-docker/blob/master/Dockerfile
